# Generated by Django 4.1.dev20220405124126 on 2022-04-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_desctiprion_company_descriprion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='descriprion',
            new_name='description',
        ),
    ]
